### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/pyeasyeda#20]
Dear Group 7, here is some feedback from milestone 1

**Teamwork contract: Correctness**

_State the team member's names_

**Function specifications: Quality**

_For the different functions that are described in the readme, what format is the dataset in? This is crucial!_

_Lastly what sorts of error messages will you give?_

**Manage issues: Mechanics**

_Great job using issues, use milestones or create a project board, but James Kim did not have any commits_ 

Great job, keep up the work!

**Comment by Luming-ubc** [comment]
Hi Andy, 

Thanks for the feedback. We added team members for the teamwork contract. https://docs.google.com/document/d/1Mb2u0dIq-y_wJaqtgAGd6fxs9wnIPoevrdhv01i9lXA/edit

We will also add what sorts of error messages in Readme.md this week as well.

I believe James' work mainly focused on the project board, issue management and submissions. We will also make sure that we all have commits for Milestone 2.

**Comment by andytai7** [comment]
Thank you! 

Have a good week and good luck with the next milestone!

Best, 
Andy
