### ISSUE TITLE
Milestone 2 - First meeting

### ISSUE THREAD

**Issue by khbunyan** [UBC-MDS/pyeasyeda#22]
**Meeting Notes:**
- Everyone takes their assigned function from the issues created last milestone
- Please use the same dataset to test: housing in Vancouver from 561 (to be confirmed by Kristin)
- update the README file to define that the package is best suited for a Regression type problem with a continuous response variable
- For the R Package github section, everyone is doing the same section as last week
- Sukhleen is travelling on Wednesday (safe travels!)

**Comment by khbunyan** [comment]
Link to project example: https://github.com/UBC-MDS/software-review-2021/issues

**Comment by Luming-ubc** [comment]
Meeting agenda is completed by end of Milestone 2.
