### ISSUE TITLE
Source appropriate dataset

### ISSUE THREAD

**Issue by jamesktkim** [UBC-MDS/pyeasyeda#25]

**Comment by jamesktkim** [comment]
https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data

**Comment by khbunyan** [comment]
Hi all, I've tried an failed to load in a @pytest.fixture version of that NYC dataset but it keeps failing. I'm going to use my custom toy set for now, but if someone figures it out let me know and I'll integrate into mine

**Comment by Luming-ubc** [comment]
Maybe we could use the new_york_city_airbnb data for the integration test (in later milestones). Toy_data_set might work for Milestone 2.
