### ISSUE TITLE
Meeting agenda for Milestone 3

### ISSUE THREAD

**Issue by Luming-ubc** [UBC-MDS/pyeasyeda#45]
1. Divide the issues of Milestone 3 amongst the team.
- Python package checklist: 
-- Documentation : James
-- Github Action Workflow : Sukhleen, Kristin
-- Submission and proof reading : Luming

2. Meeting on Friday (10 am)

**Comment by sukhleen999** [comment]
Edited the meeting notes. Please feel free to add anything that might be missed here.
