### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by jamesktkim** [UBC-MDS/pyeasyeda#56]
Hello Team,
On Documentation part of Milestone 3, there are basically two portions: Updating the usage section on Readme and creating formal Documentation.

Updating the Usage section on Readme <- discussion going on in slack. I created a placeholder for now.
Once agreed, I need to update the example file in our repo via jupyter notebook and use the results to
1. update the Usage section on Readme with codes and visuals
2. update the slides for presentation on demo
3. update the formal documentation hosted by Read the Docs (live, should be automatically updated)
I suggest we jump on a quick call on Thrsday or discuss it on Friday meeting.

Formal documentation is created and deployed by Read the Docs and Documentation section is added in Readme File (Please approve PR request).
It can be found at: https://pyeasyeda.readthedocs.io/en/latest/index.html

**Comment by khbunyan** [comment]
As discussed on Slack, we have decided to use the penguins.csv data set from DSCI 511. This has be uploaded and resolved.

Closing out this issue now
