### ISSUE TITLE
Milestone 3# Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/pyeasyeda#71]
Specific expectations for this milestone: Mechanics

Comments
Commits on the Python repo are not balanced.

**Comment by Luming-ubc** [comment]
Hi Andy, @andytai7 

Thanks for the feedback. Please let us explain. I believe we divided the work evenly, and we believe each of us has equal contributions to the project. Commit number is not an accurate measure of our efforts, and please accept this explanation. 

Thanks!
